builder:
  track: dev

labels:
  app: nike-plus-to-runkeeper-sync
  language: golang

version:
  semver:
    major: 0
    minor: 0
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master

pipelines:
  set-pending-build-status:
    image: extensions/github-status:dev
    status: pending
    when:
      server == 'estafette'

  build:
    image: golang:1.9.1-alpine3.6
    workDir: /go/src/github.com/JorritSalverda/${ESTAFETTE_LABEL_APP}
    commands:
    - go test `go list ./... | grep -v /vendor/`
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .

  bake:
    image: docker:17.09.0-ce
    commands:
    - cp Dockerfile ./publish
    - cp /etc/ssl/certs/ca-certificates.crt ./publish
    - docker build -t jsalverda/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION} ./publish

  push-to-docker-hub:
    image: docker:17.09.0-ce
    env:
      DOCKER_HUB_USERNAME: estafette.secret(r74nrQqDg4PsTcFs.Z4rYdNcCsLUffUGEM9nMXZzBvHo5NH4LBA==)
      DOCKER_HUB_PASSWORD: estafette.secret(9a1Hi27C6D_7T92U.RkTR8dK6RISOiLH9BX7kindCGBgAXhpOpCFetPfmh8bk_Tog)
    commands:
    - docker login --username=${DOCKER_HUB_USERNAME} --password="${DOCKER_HUB_PASSWORD}"
    - docker push jsalverda/${ESTAFETTE_LABEL_APP}:${ESTAFETTE_BUILD_VERSION}
    when:
      status == 'succeeded' &&
      branch == 'master' &&
      server == 'estafette'

  set-build-status:
    image: extensions/github-status:dev
    when:
      server == 'estafette'