apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nike-plus-to-runkeeper-sync.fullname" . }}
  labels:
    app: {{ template "nike-plus-to-runkeeper-sync.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  # config.yaml: |-
  #   lastSyncedItemIndex: 0